# colang_version: "2.0"

models:
  - type: main
    engine: openai
    model: ${LLM_MODEL}
    parameters:
      base_url: ${LLM_BASE_URL}
      openai_api_key: None

# rails:
#   output:
#     flows:
#       - check sentiment judge output

streaming: True

actions:
  - type: python
    module: actions